<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><h1 class="text-xl font-semibold text-gray-800">Edit Campaign Draft / <span lang="ar" dir="rtl">تعديل مسودة الحملة</span></h1><a class="text-indigo-600 focus:outline-none focus:ring-2 focus:ring-indigo-500" href="{{ route('admin.campaigns.index') }}">Back to Campaigns / العودة للحملات</a></div></x-slot>
    <div class="py-12"><div class="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8"><div class="rounded-lg bg-white p-6 shadow-sm">
        <p class="mb-3 text-sm">Saving edits this draft only and does not publish it. / <span lang="ar" dir="rtl">الحفظ يعدّل المسودة فقط ولا ينشرها.</span></p>
        <p class="mb-6 text-sm">Immutable slug / <span lang="ar" dir="rtl">المعرّف غير قابل للتعديل</span>: <b dir="ltr">{{ $campaign->slug }}</b></p>
        @if ($currentCategory && ($currentCategory->trashed() || ! $currentCategory->is_active))<div role="alert" class="mb-4 rounded bg-amber-50 p-4 text-sm">The current Category is unavailable; choose an eligible Category before saving. / الفئة الحالية غير متاحة؛ اختر فئة متاحة قبل الحفظ.</div>@endif
        @if ($categories->isEmpty())
            <div role="status" class="rounded bg-amber-50 p-4 text-sm">No eligible Categories are available. This draft cannot be saved. / لا توجد فئات متاحة ولا يمكن حفظ المسودة.</div>
        @else
            @php $oldCategory=old('category_id',$campaign->category_id); $oldCategory=is_string($oldCategory)||is_int($oldCategory)?(string)$oldCategory:''; @endphp
            <form method="POST" action="{{ route('admin.campaigns.update', $campaign) }}" class="space-y-5">@csrf @method('PATCH')
                @if($errors->any())<div role="alert" class="rounded bg-red-50 p-4 text-sm"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
                <div><label for="category_id">Category / الفئة</label><select id="category_id" name="category_id" required class="mt-1 block w-full focus:ring-2 focus:ring-indigo-500" @if($errors->has('category_id')) aria-invalid="true" aria-describedby="category_id-error" @endif><option value="">Select / اختر</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($oldCategory===(string)$category->id)>{{ $category->name_en }} / {{ $category->name_ar }}</option>@endforeach</select>@error('category_id')<p id="category_id-error">{{ $message }}</p>@enderror</div>
                @foreach(['title_en'=>['English title / العنوان الإنجليزي','en','ltr',255],'title_ar'=>['Arabic title / العنوان العربي','ar','rtl',255]] as $name=>$meta) @php $value=old($name,$campaign->{$name}); $value=is_string($value)?$value:''; @endphp <div><label for="{{ $name }}">{{ $meta[0] }}</label><input id="{{ $name }}" name="{{ $name }}" value="{{ $value }}" required maxlength="{{ $meta[3] }}" lang="{{ $meta[1] }}" dir="{{ $meta[2] }}" class="mt-1 block w-full focus:ring-2 focus:ring-indigo-500" @if($errors->has($name)) aria-invalid="true" aria-describedby="{{ $name }}-error" @endif>@error($name)<p id="{{ $name }}-error">{{ $message }}</p>@enderror</div> @endforeach
                @foreach(['summary_en'=>['English summary / الملخص الإنجليزي','en','ltr',1000],'summary_ar'=>['Arabic summary / الملخص العربي','ar','rtl',1000],'story_en'=>['English public story / القصة العامة الإنجليزية','en','ltr',20000],'story_ar'=>['Arabic public story / القصة العامة العربية','ar','rtl',20000]] as $name=>$meta) @php $value=old($name,$campaign->{$name}); $value=is_string($value)?$value:''; @endphp <div><label for="{{ $name }}">{{ $meta[0] }}</label><textarea id="{{ $name }}" name="{{ $name }}" required maxlength="{{ $meta[3] }}" lang="{{ $meta[1] }}" dir="{{ $meta[2] }}" class="mt-1 block w-full focus:ring-2 focus:ring-indigo-500" @if($errors->has($name)) aria-invalid="true" aria-describedby="{{ $name }}-error" @endif>{{ $value }}</textarea>@error($name)<p id="{{ $name }}-error">{{ $message }}</p>@enderror</div> @endforeach
                @php $amount=old('target_amount',$campaign->target_amount); $amount=is_string($amount)||is_int($amount)||is_float($amount)?(string)$amount:''; @endphp
                <div><label for="target_amount">Target amount (SDG) / المبلغ المستهدف</label><input id="target_amount" name="target_amount" dir="ltr" inputmode="decimal" value="{{ $amount }}" required class="mt-1 block w-full focus:ring-2 focus:ring-indigo-500" @if($errors->has('target_amount')) aria-invalid="true" aria-describedby="target_amount-error" @endif>@error('target_amount')<p id="target_amount-error">{{ $message }}</p>@enderror</div>
                <button class="rounded bg-indigo-600 px-4 py-2 text-white focus:outline-none focus:ring-2 focus:ring-indigo-500">Save Changes / حفظ التغييرات</button>
            </form>
        @endif
    </div></div></div>
</x-app-layout>
